export const WORDS1 = [
    'گونا گون',
    'مضبوط',
    'خليل',
    'احباء',
    'توجه',
    'تواضع',
    'راه',
    'گلوري',
    'طمانچه',
    'تنور',
    'منجنيق',
    'قلب',
    'علامة',
    'مملكة',
    'استعمار',
    'مقياس',
    'نيل',
    'بقعة',
  ];
  
  export const WORDSDEF = {
    'گونا گون': 'endless',
    'مضبوط': 'steadfast',
    'خليل': 'friend',
    'احباء': 'most preferred',
    'توجه': 'Entire focus',
    'تواضع': 'humility',
    'راه': 'path',
    'گلوري': 'Lizard',
    'طمانچه': 'strike/slap',
    'تنور': 'earth oven',
    'منجنيق': 'catapult',
    'قلب': 'heart',
    'علامة': 'very learned',
    'مملكة': 'Kingdom',
    'استعمار': 'Colonisation',
    'مقياس': 'A form of measurement',
    'نيل': 'The Nile, the river flowing through Egypt',
    'بقعة': 'an area, or a patch of colour in contrast to its background',
  };
  