export const WORDS1 = [
  'چنگاري',
  'انفع',
  'خيرخواه',
  'پرديسي',
  'سيلاب',
  'پهين',
  'دكال',
  'هتهيلي',
  'چونا',
  'كرار',
  'فرار',
  'رمد',
  'خطوة',
  'اوزار',
  'دگمگائي',
  'خيشوم',
  'عفيف',
  'بنديوان',
  'پروس',
  'اجاگرا',
  'درويش',
  'تلقين',
  'بےزبان',
];

export const WORDSDEF= {
  'چنگاري': 'spark',
  'انفع': 'the most beneficial/useful',
  'خيرخواه': 'well-wisher',
  'پرديسي': 'foreigner, outsider',
  'سيلاب': 'flood',
  'پهين': 'foam',
  'دكال': 'drought',
  'هتهيلي': 'palm',
  'چونا': 'limestone',
  'كرار': 'one who constantly and continuously attacks',
  'فرار': 'not one to flee',
  'رمد': 'conjunctivitis',
  'خطوة': 'step',
  'اوزار': 'instruments',
  'دگمگائي': 'to be shaken',
  'خيشوم': 'bridge of the nose',
  'عفيف': 'abstinent, pious',
  'بنديوان': 'captive',
  'پروس': 'neighbor',
  'اجاگرا': 'to remain awake throughout the night',
  'درويش': 'faqir',
  'تلقين': 'prompt',
  'بےزبان': 'mute',
};
