export const WORDS1 = [
    'كبد',
    'توقيف',
    'نص',
    'تمنى',
    'عبد',
    'ٰافرين',
    'بخيل',
    'پرچم',
    'اتقياء',
    'اخفياء',
    'مسرف',
    'عادة شريفة',
    'دور دراز',
    'جمل',
    'رحمكم',
    'تقوى',
    'بكتر',
    'پراموو',
    'مغفرة',
    'معركة',
    'لرزتا',
    'تاكيد',
    'قانون',
    'بهونو',
    'كليجه',
    'چهلني',
    'كمپاره',
    'نونهال',
    'بےدم',
  ];
  
  export const WORDSDEF = {
    كبد: 'liver',
    توقيف: 'to specify a mansoos',
    نص: 'to appoint a mansoos',
    تمنى: 'hope',
    عبد: 'slave',
    افرين: 'well done/beautiful',
    بخيل: 'miser',
    پرچم: 'flag/banner',
    اتقياء: 'pious',
    اخفياء: 'fearful',
    مسرف: 'wasteful',
    'دوردراز': 'far away',
    جمل: 'camel',
    رحمكم: 'May Allah bless you',
    تقوى: 'piousness',
    بكتر: 'armour',
    پراموو: 'to liberate',
    مغفرة: 'eternal peace',
    معركة: 'battlefield',
    لرزتا: 'trembling',
    تاكيد: 'certainty',
    قانون: 'law/rule',
    بهونو: 'destroy/mutilate',
    كليجه: 'liver',
    چهلني: 'sieve',
    كمپاره: 'anxiety',
    نونهال: 'apple of the eye',
    بےدم: 'lifeless',
  };
  