export const WORDS1 = [
	"مثال",
	"فرس",
	"مضبوط",
	"طيب",
	"ياقوت",
	"كهجوري",
	"نحلة",
	"ودهامني",
	"يكتا",
	"شير",
	"سسلو",
	"هرن",
	"مور",
	"بلبل",
	"اعرابي",
	"انصاري",
	"غذاء",
	"رجس",
	"اشارة",
	"حلال",
	"ليندي",
	"خشوع",
	"غيبة",
	"هيولى",
];
export const WORDSDEF = {
	مثال: "example",
	فرس: "horse",
	مضبوط: "strong",
	طيب: "clean,pure",
	ياقوت: "ruby",
	كهجوري: "date palm",
	نحلة: "honeybee",
	ودهامني: "Glad tidings",
	يكتا: "one of a kind",
	شير: "lion",
	سسلو: "rabbit",
	هرن: "deer",
	مور: "peacock",
	بلبل: "nightingale",
	اعرابي: "Bedouin",
	انصاري: "Those in Medina who were among the first to give assistance to Rasulallah SAW",
	غذاء: "Sustenance, nourishment",
	رجس: "impurity",
	اشارة: "filth",
	حلال: "permissible in shariat",
	ليندي: "droppings",
	خشوع: "humbleness",
	غيبة: "gossip",
	هيولى: "physical world",
};
