export const WORDS1 = [
	'پانسلي',
'بزدل',
'كنجوسي',
'تيك',
'خصلة',
'وانكو',
'لحاظ',
'پرده',
'ميزان',
'برودة',
'حرارة',
];
export const WORDSDEF = {
'پانسلي':'rib',
'بزدل':'fearful, apprehensive ',
'كنجوسي':'stinginess ',
'تيك':'self respect ',
'خصلة':'trait',
'وانكو':'bent, curved ',
'لحاظ':'modesty',
'پرده':'veil ',
'ميزان':'scales for measurement of weight ',
'برودة':'cool temperament ',
'حرارة':'heated temperament ',
};
