export const WORDS1 = [
	'كستوري',
'خوشبو',
'دارين',
'دير',
'چنگاري',
'كير',
'جليس',
'طب',
'سواد',
'قيمة',
'پيشاني',
'سانپ',
'ليسو',
'تجوو',
'رضاء',
'بارش',
'اكيلا',
'خنزير',
];
export const WORDSDEF = {
	'كستوري':'musk ',
'خوشبو':'fragrance ',
'دارين':'place in Bahrain famous for musk',
'دير':'monastery ',
'چنگاري':'spark',
'كير':'bellows ',
'جليس':'companion ',
'طب':'medicine ',
'سواد':'taste',
'قيمة':'value',
'پيشاني':'forehead ',
'سانپ':'snake',
'ليسو':'soft',
'تجوو':'to relinquish or abandon ',
'رضاء':'joy, happiness ',
'بارش':'rain',
'اكيلا':'alone',
'خنزير':'swine ',
};
