name: Run Hourly Python Scripts

# Schedule to run the workflow every hour
on:
  schedule:
    - cron: "45 * * * *" # This runs every hour, on the 45th minute (UTC)

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Replace with the version you need (e.g., '3.9')

      # Step 3: Install Dependencies (if any)
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt # Use requirements.txt if you have one, otherwise manually install any necessary dependencies
          pip install requests  # Include any additional dependencies for both scripts
          pip install pandas
          pip install openpyxl
          pip install tqdm

      # Step 4: Run koha.py
      - name: Run koha.py
        run: python koha.py # Ensure you're running the correct script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
